name: Count publicodes lines
on:
  push:
  schedule:
    - cron: 0 0 1 * * # https://crontab.guru/every-month
jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npx zx ./count-publicodes-lines.mjs --quiet --update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: Github Actions <actions@github.com>
